name: CI

on: 
  push:

jobs:
  sast_scan: 
    name: Ejecutar Escaneo Bandit
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2
      
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Instalación de Bandit
      run: pip install bandit

    - name: Ejecutar Escaneo Bandit
      run: bandit -ll -ii -r . -f json -o bandit-reprt.json
      
    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      if: always()
      with: 
        name: hallazgos-bandit
        path: bandit-reprt.json
  image_scan:
      name: image build and running
      runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name Docker scout scan
        run  
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
          docker scout quickview
          docker scout cves
