name: CI

on:  [push]

jobs:
  sast_scan: 
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: check code
      uses: actions/checkout@v2
      
    - name: python setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Bandit installation
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r .
